// Template & Resume
export const SELECTTEMPLATE = "SELECTTEMPLATE";
export const SELECTRESUME = "SELECTRESUME";

// Personal Info
export const ADDPERSONALINFO = "ADDPERSONALINFO";

// Work Experience
export const ADDEXPERIENCE = "ADDEXPERIENCE";
export const ADDALLEXPERIENCE = "ADDALLEXPERIENCE";

// Skills
export const ADDNEWSKILLS = "ADDNEWSKILLS";
export const EDITSKILL = "EDITSKILL";
export const DELETESKILL = "DELETESKILL";

// Education
export const ADDEDUCATION = "ADDEDUCATION";

// Projects
export const ADDPROJECT = "ADDPROJECT";
export const ADDALLPROJECTS = "ADDALLPROJECTS";
export const DELETEPROJECT = "DELETEPROJECT";

// Certifications
export const ADD_CERTIFICATION = "ADD_CERTIFICATION";
export const EDIT_CERTIFICATION = "EDIT_CERTIFICATION";
export const DELETE_CERTIFICATION = "DELETE_CERTIFICATION";
export const ADDALLCERTIFICATIONS = "ADDALLCERTIFICATIONS";

// Achievements
export const ADDACHIEVEMENT = "ADDACHIEVEMENT";
export const ADDALLACHIEVEMENTS = "ADDALLACHIEVEMENTS";
export const DELETEACHIEVEMENT = "DELETEACHIEVEMENT";

// Languages
export const ADDLANGUAGE = "ADDLANGUAGE";
export const ADDALLLANGUAGES = "ADDALLLANGUAGES";
export const DELETELANGUAGE = "DELETELANGUAGE";
